Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  if Vagrant.has_plugin?("vagrant-vbguest")
      config.vbguest.auto_update = false
      config.vbguest.no_install  = true
    end

  # Blue VM - hosts the current/initial version
  config.vm.define "blue" do |blue|
    blue.vm.hostname = "blue-vm"
    blue.vm.network "private_network", ip: "192.168.56.11" , auto_config: false
    blue.vm.network "forwarded_port", guest: 8080, host: 8081
    blue.vm.provision "shell", run: "always", inline: "ip addr add 192.168.56.11/24 dev enp0s8; ip link set enp0s8 up"


    blue.vm.synced_folder "./h2-data-blue", "/home/vagrant/h2-data", create: true, disabled: true
    
    blue.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
      vb.name = "blue-vm"
      vb.gui = true
      vb.customize ["modifyvm", :id, "--vram", "32"]
    end
    
    # Provision blue VM
    # blue.vm.provision "ansible" do |ansible|
     # ansible.playbook = "blue.yml"
     # ansible.inventory_path = "host.ini"
     # ansible.limit = "blue"
   # end
  end

  # Green VM - deployment target for Jenkins pipeline
  config.vm.define "green" do |green|
    green.vm.hostname = "green-vm"
    green.vm.network "private_network", ip: "192.168.56.12" , auto_config: false
    green.vm.network "forwarded_port", guest: 8080, host: 8082
    green.vm.provision "shell", run: "always", inline: "ip addr add 192.168.56.12/24 dev enp0s8; ip link set enp0s8 up"

    green.vm.synced_folder "./h2-data-green", "/home/vagrant/h2-data", create: true , disabled: true
    
    green.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
      vb.name = "green-vm"
      vb.gui = true
        vb.customize ["modifyvm", :id, "--vram", "32"]

    end
    

   ## green.vm.provision "ansible" do |ansible|
    ##  ansible.playbook = "green.yml"
     ## ansible.inventory_path = "host.ini"
      ##ansible.limit = "green"
    #end


  end
end